# Generated by Django 2.1.5 on 2020-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=2500),
        ),
    ]
