# Generated by Django 2.1.5 on 2020-01-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200109_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AddField(
            model_name='song',
            name='song_link',
            field=models.FileField(max_length=140, null=True, upload_to=''),
        ),
    ]
