# Generated by Django 2.1.5 on 2020-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200109_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.FileField(default='see.mp3', upload_to=''),
        ),
    ]
