# Generated by Django 2.1.5 on 2020-05-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200109_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_logo',
            field=models.ImageField(default='2.jpg', upload_to=''),
        ),
    ]
